### ISSUE TITLE
'PHTO SCHOOL ZN SPEED VIOLATION' should probably map to 'Speed Camera Violation'

### ISSUE THREAD

**Issue by michaelkolber** [bdhowald/hows_my_driving#1]
Currently, violation code 'PHTO SCHOOL ZN SPEED VIOLATION' maps to 'School Zone Speed Camera Violation'. However, since NYS legislated that cameras can be installed in non-school high-traffic zones, some have started popping up in non-school areas. However, the DOF never updated their Parking Violation Codes, so it remains 'PHTO SCHOOL ZN SPEED VIOLATION'.

However, on the website, it would probably make more sense to list it as 'Speed Camera Violation' since speed cams are no longer limited to school zones.

**Comment by bdhowald** [comment]
I apologize for not responding to this sooner.

If I'm not mistaken, the number of school zones was expanded from 140 to 750 along with removing the restriction that the cameras had to be placed on streets that have an entrance to the school and allowing them to be placed within a 1/4 mile radius of the school.

Technically, it's just a legal expansion of what's considered a school zone rather than allowing them elsewhere, but you're right that the cameras are less associated with specific schools than they once were. If the legislature drops the requirement that the cameras be connected to schools in any way, I'll drop the "School Zone" part.
